version: 2

sources:
  - name: ecommerce # Ou olist_ecommerce, peu importe
    description: "Données brutes Olist E-commerce chargées depuis GCS."
    
    # On met le nom du dataset qui existe VRAIMENT dans BigQuery
    schema: notlimitail_datadubrazil # <--- LA CORRECTION EST ICI
    
    tables:
      - name: customers
      - name: orders
      - name: orders_items # Attention, il y a peut-être un "s" manquant ici aussi
      - name: orders_payments
      - name: products```

