version: 2

sources:
  - name: olist_ecommerce  # C'est le nouveau nom de notre source, plus clair.
    description: "Données brutes Olist E-commerce chargées depuis GCS."
    
    # On met le nom du dataset qui existe VRAIMENT dans BigQuery
    schema: notlimitail_datadubrazil
    
    # On liste les tables avec leurs noms exacts
    tables:
      - name: customers
      - name: orders
      - name: orders_item      # <-- Corrigé (sans le "s")
      - name: orders_payments
      - name: products